site_name: feed
site_description: Basic social network with geo features
repo_url: https://github.com/VJPranay/sps
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/VJPranay">VJPranay</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
