# Generated by Django 2.1.9 on 2019-07-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_activity_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='date',
            new_name='datetime',
        ),
    ]
