# Generated by Django 2.1.9 on 2019-07-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
